Update .github/workflows/dotnet-core.yml
Run test-suites explicitly instead of discovering them.  This attempts to
workaround an issue where the tests run fine locally but fail on CI:

    Total tests: 182. Passed: 182. Failed: 0. Skipped: 0.
    Test Run Successful.
    Test execution time: 9.2574 Seconds
         1>Done Building Project "D:\a\fsharp-hedgehog\fsharp-hedgehog\Hedgehog.sln" (VSTest target(s)) -- FAILED.

    Build FAILED.
        0 Warning(s)
        0 Error(s)

    Time Elapsed 00:00:21.27
    Error: Process completed with exit code 1.

See also: https://github.com/hedgehogqa/fsharp-hedgehog/pull/219